# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: 'Build'
    displayName: 'Build'
    jobs:
    - job: 'Build'
      displayName: 'Build'
 
      variables:
        Solution: '**/*.sln'
        BuildPlatform: 'Any CPU'
        BuildConfiguration: 'Release'
      steps:
        - task: PowerShell@2
          inputs:
                 targetType: 'inline'
                 script: 
                  Write-Host "Hello World"
                  Start-Sleep -Seconds 20
                  Write-Host "Hello World"
                  
  - stage: 'Deploy'
    displayName: 'Deploy'
    dependsOn: 'Build'
    jobs:
    - deployment: 'Deploy'
      displayName: 'Deploy'
      continueOnError: false
      timeoutInMinutes: 10
      workspace:
        clean: all

      environment:
        name: SERVER-DEV

      strategy:
        runOnce:
          deploy:
            steps:
              - task: PowerShell@2
                inputs:
                 targetType: 'inline'
                 script: 
                  Write-Host "Hello World"
                  Start-Sleep -Seconds 20
                  Write-Host "Hello World"
            