# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:

- stage: Deploy3
  jobs:
  - deployment: Deploy3
    displayName: Deploy3
    timeoutInMinutes: 10
    environment: ddddd1
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
             azureSubscription: 'DTLQA (c94bda7a-0577-4374-9c53-0e46a9fb0f70)'
             WebAppName: IbbuTestFunctionApp
             packageForLinux: '$(System.DefaultWorkingDirectory)'
             AppSettings: -WEBSITE_CONTENTSHARE "$(Var1)" 
                          -FUNCTIONS_WORKER_RUNTIME "$(Var2)"
    
          - task: AzureFileCopy@4
            inputs:
              SourcePath: 'C:\Users\v-ibshaik\Desktop\Microsoft\7.txt'
              azureSubscription: 'DTLQA (c94bda7a-0577-4374-9c53-0e46a9fb0f70)'
              Destination: AzureBlob
              storage: ibbu1storage
              ContainerName: ibbuContainerRegistry
            enabled: true
