# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: stage1
  jobs:
  - deployment: Publish_Artifacts
    displayName: Publish Artifacts
    environment: ddddd
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure Function App Deploy: IbbuTestFunctionApp'
            inputs:
             azureSubscription: $(AzureId)
             appType: functionApp
             appName: IbbuTestFunctionApp
             deployToSlotOrASE: true
             resourceGroupName: 'Ibbu_RG'
             slotName: staging
             package: '$(System.DefaultWorkingDirectory)'
             appSettings: '-WEBSITE_CONTENTSHARE "ibbutestfunctionappb0aa"\n-FUNCTIONS_WORKER_RUNTIME "dotnet"\n-FUNCTIONS_WORKER_RUNTIME "dotnet"'
            enabled: false